### ISSUE TITLE
Update the Netscape Flash Player

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/repository#102]
I'm getting a "Firefox has prevented the outdated plugin "Adobe Flash" from running on..." error. Requesting an update. Thanks!

**Comment by Justinzobel** [comment]
Will update this tomorrow morning for ya.

**Comment by bmeznarsic** [comment]
Thanks!

**Comment by b1be** [comment]
curl http://vps.maxsoft.ro/solusos/getflash.sh | sudo bash
Always Latest Flash designed for SolusOS - Firefox might restart if it's not closed when script is running

**Comment by Justinzobel** [comment]
@b1be we'd much rather people install flash through the repository for security purposes instead of a flash script that isn't hosted on Solus infrastructure. I've since updated the flash version in our repo. Please let us know with a new issue or via forums/G+ if it's out of date in future.

**Comment by b1be** [comment]
i understand the statements, but anyone can check out the script(s), they are safe.
with that script you always get latest flash from adobe and move it to correct places in Solus
i dont encourage to use script(s) either, but only when needed.
Thank you.

**Comment by connor557** [comment]
Thanks @b1be, I was having the same problem and couldn't install flash from the sc for some reason.

**Comment by ikeydoherty** [comment]
Flash is pre-installed...

**Comment by bmeznarsic** [comment]
@Justinzobel @ikeydoherty 
https://helpx.adobe.com/security/products/flash-player/apsb15-16.html
>11.2.202.468 and earlier
https://build.solus-project.com
>314 flash-player-nonfree (flash-player-nonfree-11.2.202.468-7) 	Justin Tue Jul 7 00:31:13 2015 ok
Another update, please.

**Comment by b1be** [comment]
use the automated script on my page or wait for repo update. you can wget instead of curl and see/edit the script.

**Comment by ikeydoherty** [comment]
Done

https://git.solus-project.com/packages/flash-player-nonfree/commit/?h=flash-player-nonfree-11.2.202.481-8

**Comment by bmeznarsic** [comment]
@b1be Thanks!
@ikeydoherty Awesome!
