### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by connor557** [solus-project/repository#103]
This looks great, but when am I gonna be able to get it on my Solus? Also, since this is out there, is there a way I can manually build it and add it to my PiSi? PS: Y'all better get to working on those milestones. Solus isn't going to develop itself.

**Comment by Justinzobel** [comment]
Get what on Solus? If migration is an application please provide a link.

**Comment by connor557** [comment]
I want this repository on my solus. Migrate is not an app, it's what I want you to do!

**Comment by Justinzobel** [comment]
Which repository? You haven't provided any information, is it a 3rd party repository? If so please send a link to it.

**Comment by b1be** [comment]
And you want to migrate to/from ?

**Comment by connor557** [comment]
You guys seem to not understand what I am saying. I want to get THIS repo in my Solus software center.

**Comment by Justinzobel** [comment]
This repo IS in the Software Center...

**Comment by ikeydoherty** [comment]
We moved the packages to https://git.solus-project.com/

> You guys seem to not understand what I am saying. I want to get THIS repo in my Solus software center.

Where do you think the software you use comes from.. ?

> PS: Y'all better get to working on those milestones. Solus isn't going to develop itself.

Quite aware of that. Those milestones are no longer relevant and you clearly don't follow the Solus blog. That said, you're not going to develop Solus either so it's a moot point, isn't it? The only break in activity we've had in a long time has been for the last few days, where I've been so ill I've been unable to even walk.

I've rewritten this comment a good 6 times already because your initial comment is nothing short of ignorant. So to save any melodrama, I'm just closing this.

**Comment by connor557** [comment]
Where all all the categories like games and graphics and that sort of thing
that I'm used to on debian/fedora/gentoo?

Regards
Connor

Connor O'Brien
Connor's Site

Sometimes the best delights in life can lead to the worst of disasters. - A
Very Wise Person

**Comment by ikeydoherty** [comment]
@connor557 the software center itself has issues, and as such not all categorisation is complete.
Now, you need to be a bit more specific there, because you've reeled off 3 distributions that are independent codebases with minimal commonality.
Solus would be a 4th, with even less commonality. Can you give me an example of something that is supposed to be there but *isn't* ?

**Comment by connor557** [comment]
Lol, here's an example: There should be a verion of solus with aptitude or yum instead of pisi for people whe want a more mature and reliable package manager.

**Comment by ikeydoherty** [comment]
...Not sure if you're trolling me. Starting to feel that way but I'll give you the benefit of the doubt.

`aptitude` is solely for the use of `dpkg`/`deb` based systems.
`yum` is solely for the use of `rpm` based systems.
You'll notice these two do not mix.

Solus uses `eopkg`, solely for the use of `eopkg` based systems. It's a fork of PiSi, and no longer compatible. It is not unreliable and certainly does not need to mature, so you've pulled phantom statements into this conversation with no founding.

Your comments seem to serve little purpose, having no prior background checking or factual accuracies, so I invite you to check on those items both before responding again.

**Comment by connor557** [comment]
I was simply saying that it'd be better if there was a version of Solus that either included yum or aptitude. Not both and not to include both or one in the current version of Solus.

**Comment by ikeydoherty** [comment]
Your comment makes no sense - that's why its coming off trollish. None of them can be included, Solus is built from scratch and is entirely incompatible with those package managers.

**Comment by ikeydoherty** [comment]
Also I'll point out two things, I'm not here to make friends, and I'm very to the point. If you don't like the answers, perhaps consider what you're doing wrong with your questions.

**Comment by connor557** [comment]
I'll also point something else out: If you don't want to make friends with your users, nobody's gonna wanna use your operating system. I'm gonna go try arch linux again.

**Comment by JoshStrobl** [comment]
>  I'm gonna go try arch linux again.

Please do.

**Comment by ikeydoherty** [comment]
I'm sorry I'll take down the welcoming banners and rainbow emitting unicorns next time.
I'm here to build a product, not a play group. Requesting features within the project requires a number of things, including prior work and research on your behalf, plus a willingness to actually work with others.

It also requires a certain intellectual and emotional capacity, both of which you have failed to demonstrate. As both prove a certain foundation for people we would like to *engage with*, that kinda relegates you to a certain creek, barring a paddle.

As such, your current requests on our project will not be tended to until you can clearly demonstrate some form of maturity that would then *deserve* a valid response, as opposed to expecting myself to be the ever-welcoming codemonkey hearkening to trollish calls.
