### ISSUE TITLE
Kingsoft Office?

### ISSUE THREAD

**Issue by harp37** [solus-project/repository#23]
Is that a possibility to add after 32-bit packages are added?

http://wps-community.org/download.html

**Comment by ikeydoherty** [comment]
I see little benefit to including another office suite, especially as LibreOffice is already in place

**Comment by harp37** [comment]
- most compatible software for Microsoft Office files
- very comfortable to use
- lightweight

**Comment by Anachron** [comment]
@ikeydoherty well it's kinda new in the office suites, I did not use it so far, but it seems to have some good ideas. Would give it a try, but lower priority than other packages.

**Comment by ikeydoherty** [comment]
http://www.ksosoft.com/office/732-end-user-license-agreement-of-kingsoft-for-free-version.html#.VTdC9ycVhBc

Sorry but that can't go in the repos
