### ISSUE TITLE
Problem with libpng12?

### ISSUE THREAD

**Issue by harp37** [solus-project/repository#24]
I use Fade In. I installed it from the generic package.

It doesn't open and it says this in the terminal:
"fadein: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory"

What do you think is the problem? On Debian, the package is called "libpng43".

**Comment by ikeydoherty** [comment]
This is a very old libpng version, we use 1.5:

```
/usr/lib/libpng15.so.15
/usr/lib/libpng15.so.15.14.0
```

Do they have a source version available ?

**Comment by harp37** [comment]
I have 1.5.14 installed. By the way, it looks like 1.2 is in Ubuntu at present if that makes a difference.

**Comment by ikeydoherty** [comment]
mm my fear is security with older libpng - what is this Fade In - can't find it.

**Comment by harp37** [comment]
You can download it from here: http://www.fadeinpro.com/page.pl?content=download. It's a free trial, but it works the same as the paid version in terms of packaging.

Plus, is it possible to have an option to downgrade the package or replace it?

**Comment by ikeydoherty** [comment]
I'll try it later and see if I can make it work. We can't package proprietary software, so it won't be going in our repos.

We're not going to add that kind of support, if you replaced libpng15 with libpng you wouldn't even be able to use X anymore, never mind lightdm, or budgie desktop :)

I also see absolutely no benefit to offering a package downgrade system, the package builds make the packages highly interdependent, which is how we've designed it. If you can think of a reason why we should provide it, please, let me know.

**Comment by harp37** [comment]
I will contact the developer of the program and see if he can make it work with the latest version. I understand.
