### ISSUE TITLE
dconf-editor after GNOME 3.16 update

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/repository#25]
$ dconf-editor 

(dconf-editor:8170): GLib-GIO-ERROR **: Settings schema 'ca.desrt.dconf-editor.Settings' is not installed

Trace/breakpoint trap (core dumped)

**Comment by ikeydoherty** [comment]
Adding related link: https://bugzilla.redhat.com/show_bug.cgi?id=1178613

**Comment by ikeydoherty** [comment]
dconf-editor split into its own package, we need to update/replace that.

**Comment by ikeydoherty** [comment]
Fixed - cheers :)
