### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by Anachron** [solus-project/repository#26]
When visiting https://evolve-os.com/mailman/listinfo/packaging I receive:

#### This Connection is Untrusted

You have asked Firefox to connect securely to evolve-os.com, but we can't confirm that your connection is secure.

Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.

#### What Should I Do?

If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by JoshStrobl** [comment]
The url is https://solus-project.com/mailman/listinfo/packaging, no longer evolve-os.com. It will still resolve, but I believe the SSL certificate is expired, as there is zero sense in updating it given solus-project.com is now used.

**Comment by Anachron** [comment]
Thanks for the info, should be updated in https://github.com/solus-project/repository/blob/master/README.md#patches then :+1:

**Comment by ikeydoherty** [comment]
Mailing list emails wont work yet.
