### ISSUE TITLE
rhythmbox

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/repository#27]
I tried to enable the alternative-toolbar plugin and got this output...

(rhythmbox:11087): libpeas-WARNING **: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ImportError("No module named 'gi'",))

(rhythmbox:11087): libpeas-WARNING **: Please check the installation of all the Python related packages required by libpeas and try again

(rhythmbox:11087): libpeas-WARNING **: Loader 'python3' is not a valid PeasPluginLoader instance

**Comment by ikeydoherty** [comment]
Can you install python3-gobject please? See if it prevails.

**Comment by bmeznarsic** [comment]
I'm sad to say it works after installing the package.

**Comment by ikeydoherty** [comment]
Screenies or it never happened :D I'll keep this open till I push the fix, thanks for confirming! =)
