### ISSUE TITLE
nautilus doesn't remember the selected folder/file icon size after closing

### ISSUE THREAD

**Issue by bmeznarsic** [solus-project/repository#28]
When you resize the folder/file icons, Nautilus doesn't remember the new value/setting after you close it.

**Comment by ikeydoherty** [comment]
So to do that you need to use the preferences dialog accessible from the top-left appmenu. That's where you set the defaults (counter-intuitive imo, why provide the switch in the first place..)

I've just pushed a patch to address the default size, build will be in repos soon
