### ISSUE TITLE
Add FocusWriter

### ISSUE THREAD

**Issue by harp37** [solus-project/repository#32]
Fullscreen distraction-free writing program

http://gottcode.org/focuswriter/

**Comment by funnylookinhat** [comment]
I'm inclined to create a package for FocusWriter over Trelby ( #29 ) as it at least fits a potential use-case for more people who use Solus.  The priority is quality over quantity - so maybe Trelby should wait till it has a few more requests.

However, is FocusWriter still in active development?  It looks like the last minor release was nearly a year ago.

**Comment by millingjon** [comment]
It is actively developed. See https://github.com/gottcode/focuswriter

**Comment by funnylookinhat** [comment]
Ah - was looking here ( http://gottcode.org/focuswriter/ ) and only saw a release last summer.  Cool.

**Comment by harp37** [comment]
Just to let you know: FocusWriter 1.5.4 just released.

**Comment by ikeydoherty** [comment]
Now building https://build.solus-project.com/

**Comment by ikeydoherty** [comment]
Now in the repos - major thanks to @funnylookinhat !
