### ISSUE TITLE
Arrow buttons in vim

### ISSUE THREAD

**Issue by carc1n0gen** [solus-project/repository#44]
When I am in insert mode in vim, and I use my arrow buttons letters get printed out when the cursor should move.

I don't know if this is directly related to the distribution or not.

I have only tested this on a Lenovo thinkpad L440

![screenshot from 2015-05-18 18-56-27](https://cloud.githubusercontent.com/assets/8248986/7692241/cf03f410-fd8f-11e4-84c3-05817054427c.png)

**Comment by ikeydoherty** [comment]
Setting `nocp` in your `.vimrc` will resolve this locally - but we'll need to do this by default in the repo so I'll leave this open

```
↠ cat /home/ikey/.vimrc 
set nocp
```
