### ISSUE TITLE
Ethernet Icon

### ISSUE THREAD

**Issue by func-boncey** [solus-project/repository#47]
The ethernet icon doesn't fit with the design and looks out of place with the materialism.

The button spacing also seems a bit iffy.

http://puu.sh/hT45T/f972ac8ba3.jpg

**Comment by Angristan** [comment]
I approve that. I should be more flat and littler

**Comment by topdollar3** [comment]
like the devs wrote on g+ that icon is handled by network manager, you can use faba mono icon theme to fix that

**Comment by ikeydoherty** [comment]
Faba Mono is the recommended fix. If you feel this is still a bug, please re-open @ https://bugs.solus-project.com/
