### ISSUE TITLE
I can't even boot the live CD...

### ISSUE THREAD

**Issue by krc4267** [solus-project/repository#56]
So maybe this is my fault, but I don't know. I tried to make a live USB with dd, and it stops here every time:

    [FAILED] Failed to start Switch Boot.
    See "systemctl status initrd-switch-root.service" for details.
    Warning: /dev/disk/by-label/SolusBeta does not exist
    Warning: /dev/mapper/live-rw does not exist
    
    /bin/dracut-emergency: line 28: rdsosreport: command not found
    
    
    Entering energency mode. Exit the shell to continue.
    Type "journalctl" to view system logs.
    You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot after mounting
    them and attach it to a bug report.

    /bin/dracut-emergency: line 31: exec: sh: not found

And I can't do anything. The system isn't hung, it spits out a line of text if I connect or remove a USB device. However, since it couldn't find sh (or at least that's how I interpret what it said there) I can't find the things it mentioned and attach them.

What have I done wrong?

Also, my apologies if anything is typoed in the code thing there. I had to manually type it in from a photo on my phone.

And if I needed to do anything different I'm sorry- I'm new to github and haven't hacked on this level of stuff before.

**Comment by Justinzobel** [comment]
Did you run ```sync``` after running dd and eject the USB properly? Is the ISO sha256sum the same as on the website?

**Comment by krc4267** [comment]
I didn't even know there was a command called sync, I didn't see it mounted when I unplugged it, and I (sorry) don't know how to check the sha256sum...

**Comment by Justinzobel** [comment]
Not a problem at all @krc4267 I'll leave it closed but if you still have issues tomorrow please re-open it. If you are able to jump into IRC so we can help you on the spot :)

**Comment by FrancisBaileyH** [comment]
I've actually run into this issue as well. Setting up a live USB, using dd, ran sync, and double checked the sha256sum and I still get similar errors when trying to boot. Unlike @krc4267's laptob though, the machine I'm attempting to boot from has a good history running live usb images.

**Comment by Justinzobel** [comment]
Please open a bug report on the new tracker https://bugs.solus-project.com
