### ISSUE TITLE
A small panel problem

### ISSUE THREAD

**Issue by krc4267** [solus-project/repository#57]
This is mostly cosmetic. The panel still works, but it's a little hard to read. When you put the panel on one side or the other of the screen, the clock is sideways as shown in the attached screenshot. 

As you can see, all the icons are right side up but the clock isn't.
![screenshot from 2015-05-28 16-40-20](https://cloud.githubusercontent.com/assets/2783317/7870620/8d584068-0558-11e5-977e-e94748b5105d.png)

This also happens with the panel on the right of the screen.

**Comment by Justinzobel** [comment]
Closed after discussion with user.
