### ISSUE TITLE
Nfs support ?

### ISSUE THREAD

**Issue by Myu-Unix** [solus-project/repository#59]
Hello there ! 

I'm typing this from a Solus Beta 2 install and everything is running pretty smoothly so kudos to you guys at Solus !

Would it be possible to add nfs support to mount ? It doesn't seems present as of now.

Cheers !

**Comment by sysdrum** [comment]
We are working on it, still working on samba and cups. I believe once they
have that working we will push nfs-common. Right it works but you have to
compile it.

**Comment by Myu-Unix** [comment]
Ok, glad to hear it ! I'll wait for the next update.

Cheers !
