### ISSUE TITLE
Option to have time applet display the date

### ISSUE THREAD

**Issue by howdystranger** [solus-project/repository#61]
Hi! It would be great if there was an option for the clock applet in the panel to have an option to display the date. Or, alternatively, if there was a date applet that was available I could just add that to the panel...

**Comment by ikeydoherty** [comment]
Please use `gnome-tweak-tool` to select the option to display the date. We already support displaying date.

Sidenote, this is a `budgie-desktop` issue.

**Comment by howdystranger** [comment]
Woops, sorry for filing this in the first place, let alone in the wrong place!
