### ISSUE TITLE
Volume Adjusting Problem

### ISSUE THREAD

**Issue by frozenxuan** [solus-project/repository#62]
When there's a existing popup (like apps menu) or right-click menu on the panel, I can't adjust the volume using the function key of my laptop, but function key to adjust brightness does work.

**Comment by ikeydoherty** [comment]
That's because they have keyboard grab, this is normal behaviour.

**Comment by ikeydoherty** [comment]
Sidenote, this is a `budgie-desktop` related issue, not repository.
