### ISSUE TITLE
Packages Request

### ISSUE THREAD

**Issue by frozenxuan** [solus-project/repository#63]
Can you add 'zsh' & 'uget' into the repo? I'll be glad if 'zsh' can become the default shell.(just hope)

**Comment by JoshStrobl** [comment]
ZSH is already in the repo.

**Comment by sysdrum** [comment]
sudo  eopkg it zsh

**Comment by ikeydoherty** [comment]
Currently 'dash' is the system shell (`/bin/sh`) and bash is the default user shell. zsh isn't entirely compatible in the places we'd want with bash, so that would cause problems for users running commands/scripts from guides.

**Comment by Justinzobel** [comment]
uget added and zsh already there.
