### ISSUE TITLE
Chrome Apps split into 2 categories in apps menu when >8

### ISSUE THREAD

**Issue by frozenxuan** [solus-project/repository#64]
![screenshot from 2015-06-01 18-26-55](https://cloud.githubusercontent.com/assets/6898228/7911026/2d4a2236-088c-11e5-927f-b1a51ca31d2a.png)

**Comment by ikeydoherty** [comment]
This is because they're sorted by usage. Clearly you use Google Maps and Polarr most :) This is intended behaviour.

Sidenote, this isn't a `repository` issue.
