### ISSUE TITLE
notify-send notifications aren't displayed 

### ISSUE THREAD

**Issue by Myu-Unix** [solus-project/repository#65]
Hi !

I've been trying to use notify-send but it does not seems to work. Regular Budgie notifications work fine though.

Is it the good place to report this issue ? 

I can assist by doing further tests if needed.

Cheers !

**Comment by Myu-Unix** [comment]
Actually I've found a fix on the Arch Wiki :)

Creating file /usr/share/dbus-1/services/org.gnome.Notifications.service

With this content : 

    [D-BUS Service]
    Name=org.freedesktop.Notifications
    Exec=/usr/lib/notification-daemon-1.0/notification-daemon

Notify-send works after that.

**Comment by ikeydoherty** [comment]
They are displayed.. o_o You added the notifications applet right?

**Comment by Myu-Unix** [comment]
Yep, the notification applet is enabled.

I did the cross-test and removed the "fix" that I've made, rebooted and .. notifications still work when invoked through notify-send.

I've discovered that they don't work when invoked on a root shell, but that's maybe by design, and that's maybe why I experienced it in the first place.

Sorry for the false alert !

**Comment by ikeydoherty** [comment]
Ah yeah, notifications run on the session bus, which is per-user :)
