### ISSUE TITLE
Package Request: Rust

### ISSUE THREAD

**Issue by michaelrutherford** [solus-project/repository#69]
http://www.rust-lang.org/

Could somebody add the stable release of Rust?

Rust is a systems programming language with an emphasis on safety and speed.

**Comment by JoshStrobl** [comment]
@Justinzobel Feel free to re-assign to me. I will be using Rust and have a personal interest in ensuring Rust is packaged and maintained.

@michaelrutherford Expect Rust to land soon. Working on the package right now.

**Comment by Justinzobel** [comment]
Hey Josh I tried packaging but make failed after nearly 2 hours. Good luck!

**Comment by ikeydoherty** [comment]
This is now being tracked at https://bugs.solus-project.com/show_bug.cgi?id=3
