### ISSUE TITLE
Can't boot latest ISO on main computer, boots fine on laptops and other computers

### ISSUE THREAD

**Issue by lestus** [solus-project/repository#75]
I can't boot the iso i've put on a usb key on my main computer.
It has been tested on laptops and other computers and boots fine.
The symptoms:
Grub or whatever bootloader is being used comes up fine with menu being displayed
to select Boot Solus, Boot with default UEFI and Boot into Firmware.
Selected the first option to Boot Solus.
Screen goes blank. Still has backlight on so I know it's trying to do something.
Waited for a long time - 30mins to 1hr, still on same blank screen.
There is no blinking cursor or anything to indicate what has happened or at which point
boot has stalled.
I need to know what information is necessary about my computer to help troubleshoot the problem.
I am running Ubuntu 15.04 as main and only OS on it, so if there are commands I can run in Term
to pull info into a text file and upload here let me know what those commands are and I will do it.
Basic computer specs are as follows:
Mobo: Asus X99 Intel Socket 2011 Rampage VI
CPU:  Intel 5930k 6-Core
Ram:  16Gb DDR4
HDD:  Intel 750 PCIE (Not M.2 module, Not 2.5" format through a plugin board, but actual PCIE add-on card hard drive)
Graphics: Nvidia GTX 780 Ti
I've had problems with certain linux distros not detecting my hard drive at all so preventing me from being able to install the distro (probably because they were either running an old Kernel version without NVME support or it wasn't enabled by default), but they never failed to boot, I've ran gentoo based, BSD based, Debian based, all worked at least to the point of loading the live environment. This is first distro that didn't go that far. I love solus and run it on other devices and want to make it my main os on computer as well so I can contribute to the project, please if I can provide any information that might be helpful tell me what to provide and how I can get it on Ubuntu.

**Comment by ikeydoherty** [comment]
What method did you use to put Solus on the USB?
Secondly, have you tried with BIOS-boot compatibility enabled?

**Comment by lestus** [comment]
I used direct Image restore, in "Disks" program, it's almost like a gui version of DD I would say, just blasts direct bytes at the drive, tested to boot fine on a laptop.
Secondly, I've switched modes from Auto CSM to Manual Legacy CSM support, and already had Secure Boot disabled ( if any of these were the issue though I would not even see the initial boot menu of the drive). And this time because of running in legacy mode I was able to see the verbose boot up process.
The first time I ran it, it got stuck on loading or modifying the Logitech USB Receiver driver for the keyboard. So (believe it or not) I switched the receiver from a normal USB port to a "dedicated" "keyboard" USB port (LOL yes this mobo has one of these, although I think it's just a normal USB2 instead of USB3 that all the others are.) So after that it was able to get past that part in the boot process and then the screen goes blank aand still nothing. That's literally the point I got to. So all I can assume is that it got past the initial Kernel bootup sequence magic fine, then when initialising the video out driver and loading desktop failed or stalled.

**Comment by lestus** [comment]
INXI output:

System:    Host: zenbox Kernel: 3.19.0-21-generic x86_64 (64 bit) Desktop: N/A Distro: Ubuntu 15.04 vivid
Machine:   System: ASUS product: All Series
           Mobo: ASUSTeK model: RAMPAGE V EXTREME v: Rev 1.xx Bios: American Megatrends v: 0802 date: 10/16/2014
CPU:       Hexa core Intel Core i7-5930K (-HT-MCP-) cache: 15360 KB 
           clock speeds: max: 4000 MHz 1: 1291 MHz 2: 1199 MHz 3: 1199 MHz 4: 1199 MHz 5: 1236 MHz 6: 1331 MHz
           7: 1394 MHz 8: 1200 MHz 9: 1211 MHz 10: 1275 MHz 11: 1284 MHz 12: 1388 MHz
Graphics:  Card: NVIDIA GK110B [GeForce GTX 780 Ti]
           Display Server: X.Org 1.17.1 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.0hz, 1920x1080@60.0hz
           GLX Renderer: GeForce GTX 780 Ti/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 346.59
Audio:     Card-1 NVIDIA GK110 HDMI Audio driver: snd_hda_intel Sound: ALSA v: k3.19.0-21-generic
           Card-2 Intel C610/X99 series HD Audio Controller driver: snd_hda_intel
           Card-3 Logitech driver: USB Audio
Network:   Card-1: Intel Ethernet Connection (2) I218-V driver: e1000e
           IF: eth0 state: up speed: 1000 Mbps duplex: full mac: 10:c3:7b:a2:69:21
           Card-2: Broadcom BCM4360 802.11ac Wireless Network Adapter driver: wl
           IF: wlan0 state: dormant mac: 40:e2:30:85:d8:5a
Partition: ID-1: / size: 351G used: 39G (12%) fs: ext4 dev: /dev/nvme0n1p2
           ID-2: swap-1 size: 17.04GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p3
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 33.0C mobo: N/A gpu: 35C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 258 Uptime: 7 min Memory: 599.1/15917.3MB Client: Shell (bash) inxi: 2.2.16

**Comment by lestus** [comment]
Solus Boots fine now
