### ISSUE TITLE
Package request VBA-M

### ISSUE THREAD

**Issue by sergioad** [solus-project/repository#78]
Hello @ikeydoherty could you build vbam-gtk for Solus? my recommendation is adapt the Sabayon's VBA-M package to work in Solus because it is the VBA-M wich runs better on my PC, with it I can play even GBA games something what I can not on the Fedora's Arch's and Ubuntu's VBA-M packages

Source: https://packages.sabayon.org/show/vbam,150919,sabayon-weekly,amd64,5,standard

**Comment by ikeydoherty** [comment]
Could you not have combined these all into one request? ..

**Comment by sergioad** [comment]
Of course
