### ISSUE TITLE
Package request Corebird

### ISSUE THREAD

**Issue by sergioad** [solus-project/repository#80]
@ikeydoherty could you build Corebird?

Source: https://github.com/baedert/corebird

**Comment by Justinzobel** [comment]
Corebird is already in the repo... Please STOP requesting things that are already there. We do have a search both in Software Center AND the terminal: eopkg sr corebird

**Comment by sergioad** [comment]
@Justinzobel I have allready searched for it and I did not found it

**Comment by sergioad** [comment]
Anyway I will close this one

**Comment by Justinzobel** [comment]
How did you search for it? eopkg sr corebird

**Comment by sergioad** [comment]
I s earched it from the Solus' software center

**Comment by Justinzobel** [comment]
It can take a few moments to search. SC seems to also be case sensitive so
make sure you search in all lower case.

**Comment by sergioad** [comment]
Ok :smile:
